services:
  - type: worker
    name: idisopbot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: BOT_USERNAME
        value: idisopbot
    plan: free
