services:
  - type: web
    name: idisopbot
    runtime: python
    pythonVersion: "3.11.0"
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: BOT_USERNAME
        value: idisopbot
      - key: PORT
        value: 10000
    plan: free
