services:
  - type: web
    name: idisopbot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: BOT_USERNAME
        value: idisopbot
      - key: PYTHON_VERSION
        value: 3.11.0
